apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tutorials"
  labels:
    app: "tutorials"
spec:
  selector:
    matchLabels:
      app: "tutorials"
  template:
    metadata:
      labels:
        app: "tutorials"
      annotations:
        checksum/init: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: "tutorials"
          image: "nginx:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: confd
              mountPath: /etc/nginx/conf.d
            - name: www
              mountPath: /var/www
      volumes:
        - name: confd
          configMap:
            name: tutorials-nginx-config
        - name: www
          persistentVolumeClaim:
            claimName: tutorials-www-claim
