apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "tutorials"
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.tutorials.{{ .Values.domain }}"
      secretName: ssl-config
  rules:
    - host: "*.tutorials.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "tutorials"
                port:
                  number: 80