apiVersion: v1
kind: PersistentVolume
metadata:
  name: tutorials-www
  namespace: default
spec:
  capacity:
    storage: 60Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /apibrew-storage/tutorials-www
  claimRef:
    namespace: default
    name: tutorials-www-claim