apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorials-www-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 60Gi
  storageClassName: standard